#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org License: GPLv3 =============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    #colorscheme = "jellybeans"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = false
	enable_statusline_mode = false

    project_rooter_outermost = false

    snippet_engine = "ultisnips"

    autocomplete_method = "coc"

    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'



[[layers]]
    name = "colorscheme"

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'lsp'
    enabled_clients = ['clangd', 'pylsp']

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'lang#python'
   enabled_linters = ['python', 'pylint']

[[layers]]
    name = 'lang#c'
    enable_clang_syntax_highlight = true

# C-hjkl to navigate both vim windows and tmux panes.
# Also check the tmux configuration file.
# https://github.com/christoomey/vim-tmux-navigator
[[layers]]
    name = "tmux"

[[custom_plugins]]
    #repo = 'dominikduda/vim_current_word'
    repo = 'IngoMeyer441/coc_current_word'
    # `on_cmd` option means this plugin will be loaded
    # only when the specific commands are called.
    # for example, when `:ColorHighlight` or `:ColorToggle`
    # commands are called.
    #on_cmd = ['ColorHighlight', 'ColorToggle']
    # `on_func` option means this plugin will be loaded
    # only when the specific functions are called.
    # for example, when `colorizer#ColorToggle()` function is called.
    #on_func = 'colorizer#ColorToggle'
    # `merged` option is used for merging plugins directory.
    # When `merged` is `true`, all files in this custom plugin
    # will be merged into `~/.cache/vimfiles/.cache/init.vim/`
    # for neovim or `~/.cache/vimfiles/.cache/vimrc/` for vim.
    merged = false
    # For more options see `:h dein-options`.

#[[layers]]
    #name = "denite"
    #name = "fzf"

[[custom_plugins]]
    repo = 'junegunn/fzf'
    merged = false

[[custom_plugins]]
    repo = 'junegunn/fzf.vim'
    merged = false

